node {
   def commit_id
   environment {
		DOCKERHUB_CREDENTIALS=credentials('docker-hub')
	}
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('Build') {
				sh 'docker build -t sritiman24/docker-nodejs-demo-jenkins .'
		}

		stage('Login') {

				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'

		}

		stage('Push') {

				sh 'docker push sritiman24/docker-nodejs-demo-jenkins'

    }
}
